### ISSUE TITLE
MapperScan在DataSourceConfig类中的作用是什么？

### ISSUE THREAD

**Issue by KongJHong** [Taoxj/mysql-proxy#2]
```java
@MapperScan(basePackages = "com.xjt.proxy.mapper", sqlSessionTemplateRef = "sqlTemplate")
public class DataSourceConfig {
      ....
}
```
不懂就问，这里面的MapperScan作用是什么？不是很懂

**Comment by Taoxj** [comment]
扫描mapper文件的路径啊

**Comment by Taoxj** [comment]
> ```java
> @MapperScan(basePackages = "com.xjt.proxy.mapper", sqlSessionTemplateRef = "sqlTemplate")
> public class DataSourceConfig {
>       ....
> }
> ```
> 
> 不懂就问，这里面的MapperScan作用是什么？不是很懂

**Comment by Taoxj** [comment]
> ```java
> @MapperScan(basePackages = "com.xjt.proxy.mapper", sqlSessionTemplateRef = "sqlTemplate")
> public class DataSourceConfig {
>       ....
> }
> ```
> 
> 不懂就问，这里面的MapperScan作用是什么？不是很懂

扫描mapper文件啊，比如UserMapper接口
